---
title: "Final Project"
---

## Topic

Let's find out about how some variables affect number of streams of an audio on Spotify!  
<br>
Here are the variables available to explore:  
**Stream:** number of streams of the song on Spotify.  
**Danceability:** describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.  
**Energy:** is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy.  
**Speechiness:** detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value. Values above 0.66 describe tracks that are probably made entirely of spoken words. Values between 0.33 and 0.66 describe tracks that may contain both music and speech, either in sections or layered, including such cases as rap music. Values below 0.33 most likely represent music and other non-speech-like tracks.  
**Instrumentalness:** predicts whether a track contains no vocals. "Ooh" and "aah" sounds are treated as instrumental in this context. Rap or spoken word tracks are clearly "vocal". The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content. Values above 0.5 are intended to represent instrumental tracks, but confidence is higher as the value approaches 1.0.  
**Liveness:** detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live.  
**Valence:** a measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).  
**Tempo:** the overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.  
**Duration_ms:** the duration of the track in milliseconds.  
**Length_of_Title:** length of the title of the videoclip on YouTube.  
**Views:** number of views on YouTube.  
**Likes:** number of likes on YouTube.  
**Comments:** number of comments on YouTube.  
**Links_in_Description:** number of links in the description of the video on YouTube.  
**Licensed_Binary:** Indicates whether the video represents licensed content, which means that the content was uploaded to a channel linked to a YouTube content partner and then claimed by that partner. Uses a binary of 1 for yes and 0 for no.  
**Official_Video_Binary:** binary of 1 for yes and 0 for no that indicates if the video found is the official video of the song.  
<br>
*All data is sourced from [this](https://www.kaggle.com/datasets/salvatorerastelli/spotify-and-youtube/data) Kaggle dataset.*

```{r, include=FALSE}
options(repos = c(CRAN = "https://cloud.r-project.org"))
library(tidyverse)
library(shiny)
library(shinydashboard)
library(shinyjs)

#my data
install.packages(c("devtools"))
devtools::install_github("ldurazo/kaggler")
library(readr)
library(kaggler)
kgl_auth(creds_file = 'kaggle.json')
response <- kgl_datasets_download_all(owner_dataset = "salvatorerastelli/spotify-and-youtube")
download.file(response[["url"]], "./data/temp.zip", mode="wb")
unzip_result <- unzip("./data/temp.zip", exdir = "./data/", overwrite = TRUE)
spyt <- read_csv("./data/Spotify_Youtube.csv")
```

## Dynamic Graph
Pick your own x and y variables to generate as many graphs as you want to explore the trends and relationships between the variables above! To see how variables affect number of streams on spotify, simply set the y variable to 'stream' and have fun with whichever x variable you want to explore!  
<br>
Hover over any point on the plot to look at its coordinates!  
<br>
<iframe height="750" width="100%" frameborder="no" src="https://bbtpls.shinyapps.io/bbtplsFinalApp1/"> </iframe>

## Data Story
Using the graph above, if we set y to 'stream' to plot graphs of number of spotify streams against all other variables, here are the conclusions we can draw:  
**Danceability:** A moderate level of danceability (0.6-0.8) improves the number of streams a song can get on Spotify, and there is an overall preference for more danceable songs.  
**Energy:** A similar trend can be seen with energy, which peaks at a value of around 0.8 for maximum number of streams, showing a preference for fast, loud, and noisy music on Spotify.  
**Speechiness:** Less speechy tracks tend to perform better on Spotify, and speechiness peaks in number of streams at a very small speechiness value of around 0.03. This value represents more musical and non-speech-like or rap stracks. Tracks consisting almost completely of speech such as podcasts and audiobooks perform noticeably poorly, with the maximum number of streams attained by any of them being 290.655 million streams.  
**Instrumentalness:** The trend shows a heavy preference towards less instrumental songs, with a lot of vocal content. The graph's peak is at 0, after which it decreases sharply until an instrumentalness value of about 0.02. As compared to speechiness, there is still a decent popularity for songs with higher instrumentalness, and some highly instrumental songs can still obtain quite a few streams on Spotify.  
**Liveness:** A liveness value of about 0.1 shows the highest number of streams. Less liveness is generally performs better on Spotify.  
**Valence:** The positivity or negativity of a song shows no clear correlation with number of streams on Spotify, other than some loss in popularity with songs on the extreme ends.  
**Tempo:** Tracks of 100-130bpm appear to attract the most streams, while another peak can be observed at about 170bpm. This aligns with the previous trend of danceability and energy (most dance songs are of 120bpm and above), as songs with faster bpms are shown to be preferred.  
**Duration_ms:** Songs of about 220k milliseconds, or 3 and a half minutes, obtain more streams on Spotify.  
**Length_of_Title:** A roughly 50 character length of the title of the videoclip on YouTube correlates to a higher number of streams on Spotify.  
**Views; Likes; Comments:** Number of views, likes and comments on YouTube all appear to have no effect on the number of streams a track gets on Spotify.  
**Links_in_Description:** Having up to 9-10 links in one's YouTube description shows a positive relation to number of streams on Spotify.  
**Licensed_Binary:** There is a positive relationship between the video on YouTube representing licensed content and number of streams on Spotify.  
**Official_Video_Binary:** There is a positive relationship between the video on YouTube being the official video for the song and number of streams on Spotify.  
<br>
*Note: all observations exclude outliers on the plot*
